In [29]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt

In [30]:
dataset = pd.read_csv('D:\Krill_machine_learning\Wine.csv')

In [31]:
X = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values

In [32]:
from sklearn.model_selection import train_test_split

In [33]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [34]:
from sklearn.preprocessing import StandardScaler

In [35]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

from sklearn.decomposition import PCA 
pca = PCA(n_components=2)
X_train = pca.fit_transform(X_train)
X_test = pca.transform(X_test)


In [36]:
from sklearn.linear_model import LogisticRegression

regressor = LogisticRegression(random_state=42)
regressor.fit(X_train,y_train)

LogisticRegression(random_state=42)

In [37]:
from sklearn.metrics import confusion_matrix,accuracy_score

In [38]:
y_pred = regressor.predict(X_test)
cm = confusion_matrix(y_pred,y_test)
accuracy = accuracy_score(y_pred,y_test)
print(cm)
print(accuracy)

[[14  0  0]
 [ 0 14  0]
 [ 0  0  8]]
1.0
